### ISSUE TITLE
Turn off authentication

### ISSUE THREAD

**Issue by Sijoma** [Sijoma/camunda-operator#7]
By default in new 8.8.0 we have authentication - this is good.

This is how to turn it off: 

> env:
      - name: CAMUNDA_SECURITY_AUTHENTICATION_METHOD
        value: "BASIC"
      - name: CAMUNDA_SECURITY_AUTHENTICATION_BASIC_ALLOWUNAUTHENTICATEDAPIACCESS
        value: "true"

Todo: 

- [ ] figure out how to provide credentials to users
- [ ] expose a way to turn it off either with overrideEnv / specific auth settings on CRD level

**Comment by megglos** [comment]
> name: CAMUNDA_SECURITY_AUTHENTICATION_BASIC_ALLOWUNAUTHENTICATEDAPIACCESS

got replaced by `CAMUNDA_SECURITY_AUTHENTICATION_UNPROTECTEDAPI` but it defaults to unproteced so you can omit it

**Comment by megglos** [comment]
minimal config needed would be 
```
export ZEEBE_BROKER_EXPORTERS_CAMUNDAEXPORTER_CLASSNAME=io.camunda.exporter.CamundaExporter && \
export ZEEBE_BROKER_EXPORTERS_CAMUNDAEXPORTER_ARGS_CONNECT_URL=http://localhost:9200  && \
export ZEEBE_BROKER_EXPORTERS_CAMUNDAEXPORTER_ARGS_BULK_SIZE=100  && \
export ZEEBE_BROKER_EXPORTERS_CAMUNDAEXPORTER_ARGS_INDEX_SHOULDWAITFORIMPORTERS=false  && \
export CAMUNDA_SECURITY_AUTHORIZATIONS_ENABLED=true && \
export CAMUNDA_SECUIRTY_AUTHENTICATION_UNPROTECTEDAPI=false && \
export SPRING_PROFILES_ACTIVE=identity,tasklist,operate,broker,consolidated-auth
```

**Comment by Sijoma** [comment]
This is a current example config that will get generated. Happy if you tell me I can simplify some things here. 

---

**Question 1**: Slight difference - do both work @megglos ?

ZEEBE_BROKER_EXPORTERS_CAMUNDAEXPORTER_CLASSNAME (yours) vs ZEEBE_BROKER_EXPORTERS_CAMUNDAEXPORTER_CLASS_NAME (mine)

--- 
**Question 2**: do I need to set:
>ZEEBE_BROKER_EXPORTERS_CAMUNDAEXPORTER_ARGS_BULK_SIZE ? 

I would leave it at the default for now. 

---

**Question 3**: What If I wanted to use auth - where would I get the secret from? Or do we default to static credentials simply? 

---

On current broker profiles that I set are - I think I've started to slowly add profiles and try with your profiles. These will be removed anyway right?
```        
       - name: SPRING_PROFILES_ACTIVE
          value: broker,operate
```

Full current example. At the moment I try to configure everything with Environment variables as this makes it easier to trigger the rolling update on changes. If a ConfigMap updates the changes are not propagated. 

```
metadata:
  creationTimestamp: null
  name: camunda-orchestration
spec:
  podManagementPolicy: Parallel
  replicas: 3
  selector:
    matchLabels:
      cluster: camunda-orchestration
      operator-managed: "true"
  serviceName: camunda-orchestration
  template:
    metadata:
      creationTimestamp: null
      labels:
        cluster: camunda-orchestration
        operator-managed: "true"
    spec:
      containers:
      - env:
        - name: ZEEBE_BROKER_CLUSTER_NODEID
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.labels['apps.kubernetes.io/pod-index']
        - name: ZEEBE_BROKER_CLUSTER_INITIALCONTACTPOINTS
          value: camunda-orchestration-0.camunda-orchestration..svc.cluster.local:26502,camunda-orchestration-1.camunda-orchestration..svc.cluster.local:26502,camunda-orchestration-2.camunda-orchestration..svc.cluster.local:26502
        - name: ZEEBE_BROKER_CLUSTER_PARTITIONS_COUNT
          value: "3"
        - name: ZEEBE_BROKER_CLUSTER_REPLICATION_FACTOR
          value: "3"
        - name: ZEEBE_BROKER_CLUSTER_CLUSTER_SIZE
          value: "3"
        - name: SPRING_PROFILES_ACTIVE
          value: broker,operate
        - name: ZEEBE_BROKER_EXPORTERS_CAMUNDAEXPORTER_CLASS_NAME
          value: io.camunda.exporter.CamundaExporter
        - name: ZEEBE_BROKER_EXPORTERS_CAMUNDAEXPORTER_ARGS_CONNECT_URL
          value: localhost:9205
        - name: ZEEBE_BROKER_EXPORTERS_CAMUNDAEXPORTER_ARGS_CONNECT_USERNAME
          value: my-username
        - name: ZEEBE_BROKER_EXPORTERS_CAMUNDAEXPORTER_ARGS_CONNECT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: ""
              name: my-password-secret
        - name: ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_CLASS_NAME
          value: io.camunda.zeebe.exporter.ElasticsearchExporter
        - name: ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_URL
          value: localhost:9205
        - name: ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_AUTHENTICATION_USERNAME
          value: my-username
        - name: ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_AUTHENTICATION_PASSWORD
          valueFrom:
            secretKeyRef:
              key: ""
              name: my-password-secret
        - name: CAMUNDA_DATABASE_CONNECT_TYPE
          value: elasticsearch
        - name: CAMUNDA_DATABASE_CONNECT_URL
          value: localhost:9205
        - name: CAMUNDA_DATABASE_CONNECT_CLUSTERNAME
          value: elasticsearch
        - name: CAMUNDA_DATABASE_CONNECT_USERNAME
          value: my-username
        - name: CAMUNDA_DATABASE_CONNECT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: ""
              name: my-password-secret
        - name: CAMUNDA_OPERATE_DATABASE
          value: elasticsearch
        - name: CAMUNDA_OPERATE_ELASTICSEARCH_URL
          value: localhost:9205
        - name: CAMUNDA_OPERATE_ELASTICSEARCH_PREFIX
          value: zeebe-record
        - name: CAMUNDA_OPERATE_ELASTICSEARCH_CLUSTERNAME
          value: elasticsearch
        - name: CAMUNDA_OPERATE_ELASTICSEARCH_USERNAME
          value: my-username
        - name: CAMUNDA_OPERATE_ELASTICSEARCH_PASSWORD
          valueFrom:
            secretKeyRef:
              key: ""
              name: my-password-secret
        - name: CAMUNDA_OPERATE_ZEEBEELASTICSEARCH_URL
          value: localhost:9205
        - name: CAMUNDA_OPERATE_ZEEBEELASTICSEARCH_USERNAME
          value: my-username
        - name: CAMUNDA_OPERATE_ZEEBEELASTICSEARCH_PASSWORD
          valueFrom:
            secretKeyRef:
              key: ""
              name: my-password-secret
        - name: CAMUNDA_ZEEBE_ELASTICSEARCH_URL
          value: localhost:9205
        - name: CAMUNDA_ZEEBE_ELASTICSEARCH_USERNAME
          value: my-username
        - name: CAMUNDA_ZEEBE_ELASTICSEARCH_PASSWORD
          valueFrom:
            secretKeyRef:
              key: ""
              name: my-password-secret
        image: camunda/camunda:8.8.0-alpha1
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: management
        name: camunda
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 9600
          name: management
        - containerPort: 26500
          name: gateway
        - containerPort: 26501
          name: command
        - containerPort: 26502
          name: internal
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: management
        resources: {}
        startupProbe:
          httpGet:
            path: /actuator/health/startup
            port: management
        volumeMounts:
        - mountPath: /usr/local/zeebe/data
          name: data
  updateStrategy: {}
  volumeClaimTemplates:
  - metadata:
      creationTimestamp: null
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
    status: {}
status:
  availableReplicas: 0
  replicas: 0

```
